name: PNPM to bun

on: 
  push:
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show node version
        run: node --version

      - name: Setup Bun              
        uses: oven-sh/setup-bun@v1
        with: 
          run_install: false

      - name: Install dependencies
        run: bun install

      - name: Build the app
        run: bun build